[RFC][NI] Add bounding box options to map
uniplaces/ember-cli-mapbox pull request #3
Opened 2018-02-06 10:52 UTC by asantos00

# What this does?
This adds the bounding box option to map, this way you can send a bounding box and it will fit

2018-02-06 11:07 UTC, mmelo approved these changes

2018-02-07 10:44 UTC, AndreJoaquim requested changes

2018-02-07 10:44 UTC, AndreJoaquim commented on addon/components/mapbox-marker.js
> +    if (!isEmpty(cluster)) {
isPresent

2018-02-07 10:44 UTC, AndreJoaquim commented on addon/components/mapbox-marker.js
> +    } else if(map && marker) {
We don't use `else if` in our codebase :)

2018-02-07 11:08 UTC, carantunes approved these changes

2018-02-07 11:21 UTC, AndreJoaquim approved these changes

2018-02-07 11:30 UTC, merged